##### np.sort()
Return a sorted copy of  an array

In [12]:
import numpy as np

a = np.random.randint(1,100,15)
print(a)
print("-------------------------")
sorted_a = np.sort(a) # return assenting order
print(sorted_a)
print("-------------------------")
sorted = np.sort(a)[::-1] # return desending order order
print(sorted)

[40 91 19 40 81 97 93 87  3 81 90 15 35 71 98]
-------------------------
[ 3 15 19 35 40 40 71 81 81 87 90 91 93 97 98]
-------------------------
[98 97 93 91 90 87 81 81 71 40 40 35 19 15  3]


In [10]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print("-----------")
sorted_b_row = np.sort(b) # return assenting order in each row
print(sorted_b_row)
print("-----------")
sorted_b_colm = np.sort(b, axis=0) # return assenting order in each column
print(sorted_b_colm)

[[54 33 93 53]
 [68 42 86  7]
 [ 3 70 63 37]
 [91 48 47 35]
 [19 53 32 38]
 [89 52 10 86]]
-----------
[[33 53 54 93]
 [ 7 42 68 86]
 [ 3 37 63 70]
 [35 47 48 91]
 [19 32 38 53]
 [10 52 86 89]]
-----------
[[ 3 33 10  7]
 [19 42 32 35]
 [54 48 47 37]
 [68 52 63 38]
 [89 53 86 53]
 [91 70 93 86]]


##### np.append
np.appen() appends values alonge the mentioned axis at the end of the array

In [13]:
a

array([40, 91, 19, 40, 81, 97, 93, 87,  3, 81, 90, 15, 35, 71, 98])

In [19]:
np.append(a,200)

array([ 40,  91,  19,  40,  81,  97,  93,  87,   3,  81,  90,  15,  35,
        71,  98, 200])

In [20]:
# append column in 2D array in b
b

array([[54, 33, 93, 53],
       [68, 42, 86,  7],
       [ 3, 70, 63, 37],
       [91, 48, 47, 35],
       [19, 53, 32, 38],
       [89, 52, 10, 86]])

In [134]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[54., 33., 93., 53.,  1.],
       [68., 42., 86.,  7.,  1.],
       [ 3., 70., 63., 37.,  1.],
       [91., 48., 47., 35.,  1.],
       [19., 53., 32., 38.,  1.],
       [89., 52., 10., 86.,  1.]])

In [30]:
# append row in 2D array in b
np.append(b, np.ones((1,b.shape[1])), axis=0)

array([[54., 33., 93., 53.],
       [68., 42., 86.,  7.],
       [ 3., 70., 63., 37.],
       [91., 48., 47., 35.],
       [19., 53., 32., 38.],
       [89., 52., 10., 86.],
       [ 1.,  1.,  1.,  1.]])

##### np.concatenate
np.concatenate() concatenate a sequence of arrays along an existing axis.

In [31]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print("----------")
print(d)

[[0 1 2]
 [3 4 5]]
----------
[[ 6  7  8]
 [ 9 10 11]]


In [33]:
# concatinate through column
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
# concatinate through row
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

##### np.unique
With the help of np.unique(),we can get the unique values from an array given as parameter 

In [45]:
e = np.array([1,2,3,4,4,5,2,6,6,3,4,5,1,1,3,5])
print(e)

[1 2 3 4 4 5 2 6 6 3 4 5 1 1 3 5]


In [46]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

##### np.expand_dims
with the help of this method, we can get the expanded dimensions of an array

In [47]:
a = np.arange(10) # 1D array
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [50]:
# expand the 1D array into 2D
expanded = np.expand_dims(a, axis=0)
print(expanded)
print(expanded.shape)


[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [52]:
# expand the 2D into 3D
more_expanded = np.expand_dims(expanded, axis=0)
print(more_expanded)
print(more_expanded.shape)

[[[0 1 2 3 4 5 6 7 8 9]]]
(1, 1, 10)


##### np.where 
This function return the indices of elements in an input array where the given condition is satisfied

In [53]:
a = np.random.randint(1,100,15)
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [54]:
# get the index of of those number whose value is greator than 50
np.where(a>50)

(array([ 0,  3,  4,  5,  7,  9, 10, 12, 13, 14], dtype=int64),)

In [57]:
#Replce value > 50 with 0
#np.where(condition , true, false)
np.where(a>50, 0, a)

array([ 0,  4, 13,  0,  0,  0, 25,  0, 18,  0,  0, 34,  0,  0,  0])

In [58]:
#Replce even value with 0
#np.where(condition , true, false)
np.where(a%2==0, 0, a)

array([51,  0, 13,  0, 93,  0, 25,  0,  0, 85,  0,  0,  0, 67,  0])

In [135]:
x = np.array([2,4,6,8,9])
y= np.array([2,3,7,9,3])
display(x)
display(y)

np.where(x>y,x,y) # it will return greater number that either from x or from y

array([2, 4, 6, 8, 9])

array([2, 3, 7, 9, 3])

array([2, 4, 7, 9, 9])

##### np.argmax
This function return indices of the max elment of the array in a particular axis

In [62]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [63]:
# find the index of max value

np.argmax(a)

4

In [64]:
b # 2D

array([[54, 33, 93, 53],
       [68, 42, 86,  7],
       [ 3, 70, 63, 37],
       [91, 48, 47, 35],
       [19, 53, 32, 38],
       [89, 52, 10, 86]])

In [71]:
# find the index of max value in each row of 2D
np.argmax(b, axis=1)


array([2, 2, 1, 0, 1, 0], dtype=int64)

In [72]:
# find the index of max value in each column of 2D
np.argmax(b, axis=0)

array([3, 2, 0, 5], dtype=int64)

##### np.argmin

In [73]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [76]:
# find the index of min value
np.argmin(a)

1

##### np.cumsum
this function is used when we want to compute the cumulative sum of array elements over a give array 

In [77]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [78]:
np.cumsum(a)

array([ 51,  55,  68, 140, 233, 309, 334, 402, 420, 505, 581, 615, 697,
       764, 838])

In [79]:
b # 2D

array([[54, 33, 93, 53],
       [68, 42, 86,  7],
       [ 3, 70, 63, 37],
       [91, 48, 47, 35],
       [19, 53, 32, 38],
       [89, 52, 10, 86]])

In [80]:
np.cumsum(b) # convert into 1D and calcuate cumsum

array([  54,   87,  180,  233,  301,  343,  429,  436,  439,  509,  572,
        609,  700,  748,  795,  830,  849,  902,  934,  972, 1061, 1113,
       1123, 1209])

In [81]:
np.cumsum(b , axis=1) #  calcuate cumsum in rows

array([[ 54,  87, 180, 233],
       [ 68, 110, 196, 203],
       [  3,  73, 136, 173],
       [ 91, 139, 186, 221],
       [ 19,  72, 104, 142],
       [ 89, 141, 151, 237]])

In [82]:
np.cumsum(b , axis=0) #  calcuate cumsum in column

array([[ 54,  33,  93,  53],
       [122,  75, 179,  60],
       [125, 145, 242,  97],
       [216, 193, 289, 132],
       [235, 246, 321, 170],
       [324, 298, 331, 256]])

##### np.cumprod
this function is used when we want to compute the cumulative product of array elements over a give array 

In [83]:
a # 1D

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [84]:
np.cumprod(a)

array([         51,         204,        2652,      190944,    17757792,
        1349592192,  -619933568,   794190336,  1410524160,  -364530688,
       -1934528512, -1349459968,  1013432320,  -819511296,  -514293760])

In [85]:
b #2D

array([[54, 33, 93, 53],
       [68, 42, 86,  7],
       [ 3, 70, 63, 37],
       [91, 48, 47, 35],
       [19, 53, 32, 38],
       [89, 52, 10, 86]])

In [88]:
np.cumprod(b) # convert into 1D and calcuate cumprod

array([         54,        1782,      165726,     8783478,   597276504,
        -684190608,  1289149856,   434114400,  1302343200,   969710784,
         962237248,  1243039808,  1447472832,   759219200,  1323564032,
        -919899136,  -298214400,  1374505984,  1034518528,   656998400,
       -1656684544,  -248250368,  1812463616,  1253048320])

In [90]:
np.cumprod(b , axis=1) #  calcuate cumprod in rows

array([[     54,    1782,  165726, 8783478],
       [     68,    2856,  245616, 1719312],
       [      3,     210,   13230,  489510],
       [     91,    4368,  205296, 7185360],
       [     19,    1007,   32224, 1224512],
       [     89,    4628,   46280, 3980080]])

In [91]:
np.cumsum(b , axis=0) #  calcuate cumsum in colum

array([[ 54,  33,  93,  53],
       [122,  75, 179,  60],
       [125, 145, 242,  97],
       [216, 193, 289, 132],
       [235, 246, 321, 170],
       [324, 298, 331, 256]])

#### np.percentile
This function is used to compute the nth percentage of the givin data (array element) along the specified axis 

In [92]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [93]:
# calculate the 100 percent of percentile mean maximum

np.percentile(a,100)

93.0

In [94]:
# calculate the 50 percent of percentile

np.percentile(a,50)

68.0

In [96]:
# calculate the 0 percent of percentile mean minimum

np.percentile(a,0)

4.0

##### np.histogram
This function is bult-in in numpy,  which represent the frequency of data distribution in the graphical form

In [97]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [98]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 0, 1, 2, 4, 2, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

##### np.corrcoef
This function return Pearson product-moment correlation coefficients

In [99]:
salary = np.array([20000,40000, 25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

##### np.isin
with help of this fuction, we can see taht one array having values are checked in a different number array having different elements with diffeent sizes. 

In [107]:
# through np.isin we can search multiple number to mach 
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [105]:
items = [10,20,30,67,50,60,72,80,92,100]

# to chek array a has the numbers of items or not

np.isin(a,items)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False])

In [106]:
# get maching elements 
a[np.isin(a,items)]

array([72, 67])

##### np.flip
This function is used to reverses the order of array elements along the spesified axis, perserving the shape of the array

In [109]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [110]:
np.flip(a) # flip

array([74, 67, 82, 34, 76, 85, 18, 68, 25, 76, 93, 72, 13,  4, 51])

In [111]:
b #2D

array([[54, 33, 93, 53],
       [68, 42, 86,  7],
       [ 3, 70, 63, 37],
       [91, 48, 47, 35],
       [19, 53, 32, 38],
       [89, 52, 10, 86]])

In [112]:
np.flip(b) # bydefault it flip for both rows and column

array([[86, 10, 52, 89],
       [38, 32, 53, 19],
       [35, 47, 48, 91],
       [37, 63, 70,  3],
       [ 7, 86, 42, 68],
       [53, 93, 33, 54]])

In [113]:
np.flip(b, axis=1) #  flip for rows 

array([[53, 93, 33, 54],
       [ 7, 86, 42, 68],
       [37, 63, 70,  3],
       [35, 47, 48, 91],
       [38, 32, 53, 19],
       [86, 10, 52, 89]])

In [114]:
np.flip(b, axis=0) #  flip for column 

array([[89, 52, 10, 86],
       [19, 53, 32, 38],
       [91, 48, 47, 35],
       [ 3, 70, 63, 37],
       [68, 42, 86,  7],
       [54, 33, 93, 53]])

##### np.put
this function replaces spacific elements of an array with given values of p_array. Array indexed workes on flattened array.

In [115]:
a

array([51,  4, 13, 72, 93, 76, 25, 68, 18, 85, 76, 34, 82, 67, 74])

In [118]:
# replace the 0 index value with 110 and 1 index value with 500 in array a
np.put(a,[0,1], [110,500]) # this change permanently
a

array([110, 500,  13,  72,  93,  76,  25,  68,  18,  85,  76,  34,  82,
        67,  74])

##### np.delete
this function return a new array with the deletion of sub_arrays along with the mentioned axis.

In [119]:
a

array([110, 500,  13,  72,  93,  76,  25,  68,  18,  85,  76,  34,  82,
        67,  74])

In [122]:
# delete the 0 index value from array a

np.delete(a,0)

array([500,  13,  72,  93,  76,  25,  68,  18,  85,  76,  34,  82,  67,
        74])

In [123]:
# delete the 0,3,5 index value from array a

np.delete(a,[0,3,5])

array([500,  13,  93,  25,  68,  18,  85,  76,  34,  82,  67,  74])

#### Set function
1: np.union1d

2: np.intersectd

3: np.setdiff1d

4: np.setxor1d

5: np.in1d

1: np.union1d

In [124]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n) # perfirm union

array([1, 2, 3, 4, 5, 6, 7])

In [125]:
np.intersect1d(m,n) # perfirm intersection

array([3, 4, 5])

In [126]:
np.setdiff1d(m,n) # perfirm difference of m-n

array([1, 2])

In [127]:
np.setxor1d(m,n) # retun without common element

array([1, 2, 6, 7])

In [130]:
# chech 5 is in m set
np.in1d(m,5) # it like membership fuction 

array([False, False, False, False,  True])

##### np.clip
this fuction is used to clip (limit) the values in an array

In [131]:
a

array([110, 500,  13,  72,  93,  76,  25,  68,  18,  85,  76,  34,  82,
        67,  74])

In [133]:
# clip (replace) the all valuse with 75 that are above 75 
# and clip the all values with 25 that are below 25
np.clip(a, a_min=25, a_max=75) # it return all values between 25 and 75

array([75, 75, 25, 72, 75, 75, 25, 68, 25, 75, 75, 34, 75, 67, 74])