#### creating numpy method

##### with np.array

In [1]:
## 1D numpy array (vactor)
import numpy as np # type: ignore

a = np.array([2,3,4])

print(a)
print(type(a))
print(a.shape)

[2 3 4]
<class 'numpy.ndarray'>
(3,)


In [2]:
# 2D numpy array (Matrix)

m = np.array([[1,2,3],[3,4,5]])
print(m)
print(m.shape)



[[1 2 3]
 [3 4 5]]
(2, 3)


In [6]:
# 3D numpy array (tensor)

c = np.array([[[1,2,3],[4,5,6]]]) 
print(c)
print(c.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [7]:
# dtype
# creating float array
f = np.array([2,4,5], dtype=float)
print(f)

[2. 4. 5.]


In [8]:
# creating bool array
l = np.array([2,4,5,0], dtype=bool)
print(l)

[ True  True  True False]


In [9]:
# creating complex array
c = np.array([2,4,5], dtype=complex)
print(c)

[2.+0.j 4.+0.j 5.+0.j]


##### with np.arange
arange function work as range in pyton

In [10]:
# np.arange
# creating array from 1 to 10 number
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


##### with reshape


In [12]:
# np.reshape
r = np.arange(1,11).reshape(5,2)
print(r)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


##### with np.ones , np.zero , np.random

In [14]:
# np.ones : it will initilize the 1D, 2D, with 1
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# np.random : it will generate random number from 0 to 1
np.random.random((2,4))

array([[0.9104983 , 0.68498867, 0.27387252, 0.59453332],
       [0.78280614, 0.59411185, 0.26300191, 0.50609325]])

In [20]:
np.random.random((4,3))

array([[0.04582943, 0.12921111, 0.0240217 ],
       [0.73735708, 0.95685888, 0.18373214],
       [0.16593666, 0.0189474 , 0.34161822],
       [0.59850233, 0.59104702, 0.62057977]])

##### with np.linspace
linearly space

In [71]:
# np.linspace : (lower_num, uper_num, numberof_items)
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [72]:
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

##### with np.identity
create the identity matrix array

In [76]:
# creaing the 4 by 4 identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
# creaing the 6 by 6 identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### Array Attributes

In [26]:
a1 = np.arange(10) # vator
a2 = np.arange(12, dtype=float).reshape(3,4) # matrix
a3 = np.arange(8).reshape(2,2,2) # tensor
print(a1)
print("-------------")
print(a2)
print("-------------")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
-------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
-------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
# ndim
# to check the number of dimention
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [24]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


In [102]:
# size
# return the total items in a array
print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [107]:
# item size
# return the memory bytes size of array items 
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [108]:
# dtype
# return the data type of array items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing Datatype

In [27]:
a4 = np.arange(8).reshape(2,2,2)
a4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
a4.dtype

dtype('int32')

In [29]:
# change int32 into int16
a4.astype(np.int16)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

#### Array operation

In [30]:
# scalor operaton

#arithmatic operation

a1 + 2 # add each arry item with 2
a1 - 2 # subtract each arry item with 2
a1 * 2 # multiply each arry item with 2
a1 / 2 # devide each arry item with 2
a1 // 2 # modulus each arry item with 2
a1 ** 2 # power each arry item with 2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [150]:
# relational operation
# compare each items of arrya with given scalor number 
a1 > 2
a1 >= 2 
a1 < 2 
a1 == 2 
a1 != 2 

print(a1)
print(a1 > 6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [149]:
# vactor operaton

#arithmatic operation

a1 + a2 # add 2 same dimentional array
a1 - 22 # subtract 2 same dimentional array
a1 * a2 # multiply 2 same dimentional array
a1 / a2 # devide 2 same dimentional array
a1 // a2 # modulus 2 same dimentional array

print(a1 +a2)


[[ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


In [154]:
# relational operation
# compare each items of arrya with each corresponding item of secnd array 
a1 > a2
a1 >= a2 
a1 < a2 
a1 == a2 
a1 != a2 

print(a1)
print("-----------------")
print(a2)
print("-----------------")
print(a1 > a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
-----------------
[[False False False False]
 [False False False False]
 [False False False False]]


#### Array Function

In [31]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[35., 14., 91.],
       [70., 39.,  1.],
       [50., 74., 83.]])

##### max/min/sum/prod

In [32]:
# max/min/sum/prod

max_num = np.max(a1)
min_num = np.min(a1)
total_sum = np.sum(a1)
product = np.prod(a1)

print(a1)
print("-----------")
print("maximum:", max_num)
print("minimum:", min_num)
print("total sum:", total_sum)
print("product:", product)

[[35. 14. 91.]
 [70. 39.  1.]
 [50. 74. 83.]]
-----------
maximum: 91.0
minimum: 1.0
total sum: 457.0
product: 37383497970000.0


In [162]:
# 0 -> colum
# 1 -> row

# calculate the max num of each row of an arry
np.max(a1, axis=1)

array([88., 50., 87.])

In [33]:
# 0 -> colum
# 1 -> row

# calculate the max num of each column of an arry
np.max(a1, axis=0)

array([70., 74., 91.])

##### mean/median/std/var


In [34]:
mean = np.mean(a1)
median = np.median(a1)
std = np.std(a1)
varience = np.var(a1)

print(a1)
print("-----------")
print("mean:", mean)
print("median:", median)
print("std:", std)
print("var:", varience)

[[35. 14. 91.]
 [70. 39.  1.]
 [50. 74. 83.]]
-----------
mean: 50.77777777777778
median: 50.0
std: 29.408153736214715
var: 864.8395061728395


In [35]:
# 0 -> colum
# 1 -> row

# calculate the mean  of each column of an arry
np.median(a1, axis=1)

array([35., 39., 74.])

##### trigonomoetric functions

it is not enough use

In [171]:
np.sin(a1)
np.cos(a1)

array([[-0.29213881,  0.99937328, -0.84857027],
       [ 0.5551133 , -0.90369221,  0.96496603],
       [-0.65364362,  0.83422336,  0.56975033]])

##### dot product

In [174]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print("------------")
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [176]:
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

##### log and exponents

In [180]:
# calculate the log of each items of array

np.log(a3)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [181]:
# calculate the exponents of each items of array

np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

##### round/floor/ceil

In [184]:
a1 = np.random.random((2,3))*100
a1

array([[35.64441963, 75.06861948, 55.15919657],
       [62.44189515, 45.07732233, 76.23883197]])

In [186]:
# get the integer number
np.round(a1)

array([[36., 75., 55.],
       [62., 45., 76.]])

In [187]:
# get the floor integer number
np.floor(a1)

array([[35., 75., 55.],
       [62., 45., 76.]])

In [188]:
# get the ceil integer number
np.ceil(a1)

array([[36., 76., 56.],
       [63., 46., 77.]])

#### Indexing and slicing

In [36]:
a1 = np.arange(10) # 1D
a2 = np.arange(12).reshape(3,4) # 2D
a3 = np.arange(8).reshape(2,2,2) # 3D

In [37]:
# 1D indexing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# getting last element
a1[-1]

9

In [39]:
# getting 7  
a1[7]

7

In [41]:
# 2D indexing
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
# getting 5  
a2[1,1] # [no_of_row , no_of_column]

5

In [43]:
# getting 11 
a2[2,3]

11

In [44]:
# getting 9
a2[2,1]

9

In [45]:
# 3D indexing
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
# getting 5
a3[1,0,1]

5

In [47]:
# getting 3
a3[0,1,1]

3

In [48]:
# getting 6
a3[1,1,0]

6

In [49]:
# getting 1
a3[0,0,1]

1

In [50]:
# getting 0
a3[0,0,0]

0

In [51]:
# 1D slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# getting 2,3,4
a1[2:5]

array([2, 3, 4])

In [53]:
# getting 6,7,8,9
a1[6:]

array([6, 7, 8, 9])

In [54]:
# 2D slicing
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
# getting first row
a2[0,:]

array([0, 1, 2, 3])

In [60]:
# getting third column
a2[:,2]

array([ 2,  6, 10])

In [61]:
# getting 2nd column
a2[:,1]

array([1, 5, 9])

In [62]:
# getting 2nd row
a2[1,:]

array([4, 5, 6, 7])

In [63]:
# getting 5,6
a2[1,1:3]

array([5, 6])

In [64]:
# getting 9,10
a2[2,1:3]

array([ 9, 10])

In [65]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
# getting 4,8 in column
a2[1:,0]

array([4, 8])

In [67]:
# getting 9, 10, 11 from row
a2[2,1:]

array([ 9, 10, 11])

In [68]:
# getting 5   6
#         9   10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [69]:
# getting 4   5
#         8   9
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [275]:
# getting 0   3
#         8   11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [288]:
# getting 1   3
#         9   11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [291]:
# getting 4 7
a2[1,::3]

array([4, 7])

In [296]:
# getting 1  2  3
#         5  6  7
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [89]:
# 3D slicing

a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
# get second 2d arry

a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [105]:
# get third 2d arry

a3[2,:,:]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [102]:
# get first and second 2d arry

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
# get second and third 2d arry

a3[1:,:,:]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
# getting the 9, 10, 11
a3[1,0,:]

array([ 9, 10, 11])

In [91]:
# getting the 21, 22, 23
a3[2,1,:]

array([21, 22, 23])

In [92]:
# getting the 6,  7,  8
a3[0,2,:]

array([6, 7, 8])

In [93]:
# getting the 10 , 13 , 16
a3[1,:,1]

array([10, 13, 16])

In [110]:
# getting the 22   23
#             25   26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [111]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
# getting the 0    2
#             18   20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [120]:
# getting the 4    5
#             13   14
a3[:2,1,1:]

array([[ 4,  5],
       [13, 14]])

In [ ]:
# getting the 3    2
#             18   20
a3[::2,0,::2]

In [121]:
# getting the 6    7
#             15   16
#             24   25
a3[::,2,:2]

array([[ 6,  7],
       [15, 16],
       [24, 25]])

#### Iterating

In [122]:
# 1D looping
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [124]:
# 2D array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
# it print 1D arry on each iteration
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [126]:
# to print each element one by one of 2D array. 
# You have need to use 2 times for nested loop 
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [133]:
# to print each element one by one of 2D array. 
# You also will use np.nditer method
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [128]:
# 3D array
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
# it print 2D array on each iteration
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [130]:
for i in a3:
    for j in i:
        print(j)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]


In [131]:
# to print each element one by one of 3D array. 
# You have need to use 3 times for nested loop 
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [132]:
# to print each element one by one of 3D array. 
# You also will use np.nditer method
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshapping

##### 1 reshape method

In [135]:
a1 = np.arange(10)
print(a1)

# reshape

a1.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##### 2 Transpose
convert rows into columns and columns into rows

In [138]:
a2 = np.arange(6).reshape(3,2)
print(a2)
print("-----------")
transpose = np.transpose(a2)
print(transpose)

[[0 1]
 [2 3]
 [4 5]]
-----------
[[0 2 4]
 [1 3 5]]


In [141]:
##second syntex of transpose

print(a2)
print("-----------")
transpose = a2.T
print(transpose)

[[0 1]
 [2 3]
 [4 5]]
-----------
[[0 2 4]
 [1 3 5]]


##### 3 ravel

convert multi dimention arry into 1D array

In [144]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)
print("----------")
reval = np.ravel(a3)
print(reval)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
----------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [145]:
##second syntex of ravel

print(a3)
print("-----------")
ravel = a3.ravel()
print(ravel)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#### Stacking
stacking is mathod to combine the multi data sources 

it combine horizantaly using hstack method 

it combine vertically using vstack method 

In [149]:

a4 = np.arange(12).reshape(4,3)
a5 = np.arange(12,24).reshape(4,3)
a5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [148]:
# horizantal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [151]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2, 12, 13, 14,  0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17,  3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20,  6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23,  9, 10, 11, 21, 22, 23]])

In [150]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### Splitting

splitting is mathod to splite one data source into the multi data source

It is opposit of stacking

it split horizantaly using hsplit method 

it split vertically using vsplit method 

In [167]:
a1 = np.arange(16).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
# horizantal splitting

np.hsplit(a1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [169]:
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [170]:
np.hsplit(a2,2)

[array([[0],
        [2],
        [4]]),
 array([[1],
        [3],
        [5]])]

In [171]:
# vertically splitting

np.vsplit(a1,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [172]:
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [173]:
np.vsplit(a2,3)

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]